# Generated by Django 3.1.6 on 2023-11-16 13:50

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0004_auto_20230927_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preconstruction',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(status='Selling', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(status='Upcoming', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(status='Sold out', then=django.db.models.expressions.Value(3)), default=django.db.models.expressions.Value(4), output_field=models.IntegerField()), '-last_updated']},
        ),
    ]
