# Generated by Django 3.1.6 on 2023-11-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0005_auto_20231116_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='slug',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
