# Generated by Django 3.1.6 on 2024-10-23 15:39

from django.db import migrations, models
import django.db.models.expressions
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0007_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preconstruction',
            options={'ordering': ['-last_updated', django.db.models.expressions.Case(django.db.models.expressions.When(status='Selling', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(status='Upcoming', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(status='Sold out', then=django.db.models.expressions.Value(3)), default=django.db.models.expressions.Value(4), output_field=models.IntegerField())]},
        ),
        migrations.AlterField(
            model_name='developer',
            name='details',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='preconstruction',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Selling', 'Selling'), ('Archived', 'Archived'), ('Planning Phase', 'Planning Phase'), ('Sold out', 'Sold out')], default='Upcoming', max_length=500),
        ),
    ]
